# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/188oQVyQ5TENCpcynGr9zMwPZQCwEFrW_
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

df1=pd.read_csv("iris.csv")

df1.head(3)

df1.boxplot(by ='species', column =['petal_length'], grid = False) 
plt.show()

fig, ax = plt.subplots(figsize =(9, 7)) 
sns.violinplot( ax = ax, y = df1["sepal_length"] )

x = df1['petal_length']
plt.hist(x)
#plt.xlabel('petal')
#plt.title('petal length')
plt.show()

a=df1['species']
b=df1['petal_width']
plt.scatter(a,b,c='green',marker='^')
plt.show()

a=df1['species']
b=df1['petal_width']
astd = 3
bstd = 5   
width = 0.35     

p1 = plt.bar(a, width, yerr=astd)
p2 = plt.bar(b , width, bottom=astd, yerr=bstd)

plt.show

df2=pd.read_csv("wine.csv")

df2.head(3)

x = df2['Wine']
plt.hist(x)
plt.show()

a=df2['Wine']
b=df2['Color.int']
astd = 1
bstd = 5   
width = 0.35     

p1 = plt.bar(a, width, yerr=astd)
p2 = plt.bar(b , width, bottom=astd, yerr=bstd)

plt.show

a=df2['Wine']
b=df2['Alcohol']
plt.scatter(a,b,c='green')
plt.show()

df2.boxplot(by ='Wine', column =['Flavanoids'], grid = False) 
plt.show()

fig, ax = plt.subplots(figsize =(6,3)) 
sns.violinplot( ax = ax, y = df2["Flavanoids"] )

df3 = pd.read_csv("pima-indians-diabetes.csv")
df3.head(4)

x = df3['A']
plt.hist(x)
plt.show()

a=df3['A']
b=df3['D']
astd = 3
bstd = 5   
width = 0.35     

p1 = plt.bar(a, width, yerr=astd)
p2 = plt.bar(b , width, bottom=astd, yerr=bstd)

plt.show

a=df3['A']
b=df3['D']
plt.scatter(a,b,c='green')
plt.show()

df3.boxplot(by ='A', column =['B'], grid = False) 
plt.show()

fig, ax = plt.subplots(figsize =(6,3)) 
sns.violinplot( ax = ax, y = df3["A"] )



